### ISSUE TITLE
Remove field hook not working.

### ISSUE THREAD

**Issue by ansarizafar** [feathersjs/feathers-hooks#69]
I have updated feathers-cli and generated a new project [feathers-test](https://github.com/ansarizafar/feathers-test)  remove hook is not working in this project also. I am using node ver 5.7

**Comment by ekryski** [comment]
I verified with your repo that the remove hook is working great. The password is removed in:

- the authentication response
- when fetching all users
- when fetching an individual user

Maybe you were referring to what you see logged from [this line](https://github.com/ansarizafar/feathers-test/blob/master/src/app.js#L38). In that case the password won't be removed because that is considered an internal call and the `remove` hook isn't invoked on internal calls unless you override it.

I realized the docs aren't up to date there so I am updating them right now and created [an issue](https://github.com/feathersjs/feathers-docs/issues/154) to track progress.
