### ISSUE TITLE
Remove-hook breaks feathers-mongoose

### ISSUE THREAD

**Issue by supasate** [feathersjs/feathers-hooks#91]
From my previous PR (#90), the [code](https://github.com/feathersjs/feathers-hooks/blob/3a6ab3a2d904d8a022cb1f6bcb09b01de72b904e/src/bundled.js#L126) that sets `undefined` to `owner` object's properties breaks feathers-mongoose. 

The root cause is that [Mongoose creates and attaches InternalCache (called `$__`) for only its document object](https://github.com/Automattic/mongoose/blob/f35cbdefb01b0b11e419394649bc0c71f2cfedbb/lib/document.js#L40). But, when we climb its prototype chain to get the direct owner, that owner has no `$__` and [Mongoose tries to get a `scope` property of `$__`](https://github.com/Automattic/mongoose/blob/f35cbdefb01b0b11e419394649bc0c71f2cfedbb/lib/document.js#L1708-L1712). Then, an app crashes.

I'll make a PR to solve this issue.

**Comment by daffl** [comment]
Ok, I'll have a look. The best way to deal with hooks and Mongoose is using the `toObject` hook first though.

**Comment by ekryski** [comment]
Also seeing this. Funny enough I think it was a patch mongoose update that caused this to show up. Really the bundled hooks should always call either `toJSON` or `toObject` internally if those methods are present.

**Comment by supasate** [comment]
Do we have to concern about prototype inheritance in general (not only Mongoose)? There will be no `toJSON` or `toObject` available and we might have to traverse to prototype chain to find a direct owner of a property.

**Comment by supasate** [comment]
@ekryski @daffl Is there any update on this issue? If we don't care the general case of prototype inheritance, I can modify the code to check for `toJSON` and `toObject` and use them if available and remove this [test case](https://github.com/feathersjs/feathers-hooks/blob/3a6ab3a2d904d8a022cb1f6bcb09b01de72b904e/test/bundled.test.js#L263-L284). What do you think?

**Comment by daffl** [comment]
I totally thought the hook already calls it but you are right, it doesn't. I think it would the best way to go to add calling them and not worry about prototypes.

**Comment by supasate** [comment]
Okay. I'll proceed that way.

**Comment by githugger** [comment]
Sorry for digging up this closed issue.

Is there a test case for the remove-hook causing crashes when removing properties in a mongoose object?

Our application uses the hook to remove password fields of mongoose objects as well and has done so successfully without any crashes before the changes discussed here.

As I understand it, serialising all mongoose objects necessitates that a service B, that uses service A to get some object of ModelA, must now again hit the db to get a mongoose-object in order to, e.g., populate a field on that ModelA that it might need for its own service method. Or is there another way to do 'rehydrate' a serialised mongoose-object? What did you mean by
> You can always rehydrate back to a model if you need to.

@ekryski ?

If this is the only possibility to "get back" the capability of the original mongoose-object, I feel that serialising all mongoose objects going through any hooks is a significant problem for applications that make heavy use of intercommunication of tightly coupled services (internal calls go through the same hooks as external ones; *is there a way to bypass that?*). Looking through the [docs](http://docs.feathersjs.com/services/readme.html#the-setup-method) I think that this mode of service communication is intended, though.

This might be a lot of questions at once and I hope I'm in the right place, but it seems like this is the discussion that kicked of the recently(ish) changes to the handling of mongoose-objects in hooks.
Thanks in advance!

**Comment by ekryski** [comment]
Sorry @githugger this slipped by. I'll make a note to look into it later this week. Going to re-open for visibility.

**Comment by daffl** [comment]
This should be fixed with [feathers-mongoose v4.0.0](https://github.com/feathersjs/feathers-mongoose/blob/master/CHANGELOG.md#v400-2017-01-29) which sets `lean: true` by default.
