### ISSUE TITLE
[Feature Request] Hook to disable multi-update/patch/remove

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-hooks#98]
A hook that throws an error (a `400` error may be most appropriate) if the `id` is `null` for the `update`, `patch`, and `remove` service methods.

This seems generic enough to be valuable to the community at large.

**Comment by petermikitsh** [comment]
Something like this:

```js
const errors = require('feathers-errors');

function disableMultiRecordChange() {
  return function (hook) {
    if (!hook.id) {
      throw new errors.BadRequest('Multi-record changes are not permitted.');
    } else {
      return hook;
    }
  };
}
```

**Comment by daffl** [comment]
It would be a breaking change but I've been wondering about disabling it by default in general. The hook would definitely be the non-breaking way to do this. Only change I'd recommend is to check for `hook.id === null` since `hook.id = 0` would throw a bad request otherwise as well:

```js
const errors = require('feathers-errors');

function disableMultiRecordChange() {
  return function (hook) {
    if (hook.id === null) {
      throw new errors.BadRequest('Multi-record changes are not permitted.');
    } else {
      return hook;
    }
  };
}
```

If you want to add it (with a small test) in a PR to the new hook collection at https://github.com/eddyystop/feathers-hooks-common that would be great!

**Comment by eddyystop** [comment]
feathers-hooks-common now has an issue referring to this.
